# Generated by Django 5.1.3 on 2024-12-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser'),
    ]

    operations = [
    ]
