# Generated by Django 5.1.3 on 2024-12-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20241222_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
