# Generated by Django 5.1.4 on 2024-12-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='notes_videos/'),
        ),
    ]
