# Generated by Django 5.1.4 on 2024-12-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_note_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
