# Generated by Django 5.1.4 on 2024-12-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
