# Generated by Django 5.1.4 on 2024-12-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_note_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
